**Importing library:**

In [2]:
import numpy as np
%matplotlib widget
import matplotlib.pyplot as plt
from lab_utils_common import dlc, plot_data
from plt_one_addpt_onclick import plt_one_addpt_onclick
plt.style.use('./deeplearning.mplstyle')

- Datasets (1D and 2D)

In [15]:
x_train = np.array([0., 1, 2, 3, 4, 5])
y_train = np.array([0,  0, 0, 1, 1, 1])
X_train2 = np.array([[0.5, 1.5], 
                     [1.0, 1.0], 
                     [1.5, 0.5], 
                     [3.0, 0.5], 
                     [2.0, 2.0], 
                     [1.0, 2.5]])
y_train2 = np.array([0, 0, 0, 1, 1, 1])

- For (1D) data 

In [4]:
pos = y_train == 1 # True when (y_train == 1)
neg = y_train == 0 # True when (y_train == 0)
print(pos) # list of True, False where (y_train == 1)
print(neg) # list of True, False where (y_train == 0)

[False False False  True  True  True]
[ True  True  True False False False]


In [8]:
print(y_train[pos]) # Malignant (Cancerous)
print(y_train[neg]) # Benign (Non-cancerous)

[1 1 1]
[0 0 0]


In [10]:
# print those which index are true for (y_train == 1)-> Malignant
print(x_train[pos]) 
# print those which index are true for (y_train == 0)-> benign
print(x_train[neg])

[3. 4. 5.]
[0. 1. 2.]


- For 2D data

In [13]:
pos2 = y_train2 == 1
neg2 = y_train2 == 0
print(y_train2[pos2])
print(y_train2[neg2])

[1 1 1]
[0 0 0]


In [21]:
# print those which index are true for (y_train2 == 1)-> Malignant
print("those which index are true for (y_train2 == 1)-> Malignant: ")
print(X_train2[pos]) 
print("")
# print those which index are true for (y_train2 == 0)-> benign
print("those which index are true for (y_train2 == 0)-> benign: ")
print(X_train2[neg])

those which index are true for (y_train2 == 1)-> Malignant: 
[[3.  0.5]
 [2.  2. ]
 [1.  2.5]]

those which index are true for (y_train2 == 0)-> benign: 
[[0.5 1.5]
 [1.  1. ]
 [1.5 0.5]]
