In [6]:
# !pip install numpy 
import numpy as np
%matplotlib widget
import matplotlib.pyplot as plt
# from lab_utils_common import dlc, plot_data
# from plt_one_addpt_onclick import plt_one_addpt_onclick
# plt.style.use('./deeplearning.mplstyle')

In [8]:
# x_train -> One variable 

x_train = np.array([0., 1, 2, 3, 4, 5])
y_train = np.array([0, 0, 0, 1, 1, 1,])

# X_train2 -> Multiple variable 
X_train2 = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y_train2 = np.array([0, 0, 0, 1, 1, 1])

print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of x_train: {X_train2.shape}")

Shape of x_train: (6,)
Shape of x_train: (6, 2)


In [10]:
pos = y_train == 1 # only true which are y_train[i] == 1
neg = y_train == 0 # only true which are y_train[i] == 0
[pos, y_train, neg, y_train]

[array([False, False, False,  True,  True,  True]),
 array([0, 0, 0, 1, 1, 1]),
 array([ True,  True,  True, False, False, False]),
 array([0, 0, 0, 1, 1, 1])]

In [12]:
fig, ax = plt.subplot(1,2, figsize=(8, 3))

ax[0].scatter(x_train[pos], y_train[pos], marker = 'x', s = 80, c = 'red', label = "y=1")

plt.show()

TypeError: subplot() takes 1 or 3 positional arguments but 2 were given