In [2]:
# !pip install numpy 
import numpy as np
%matplotlib widget
import matplotlib.pyplot as plt
# from lab_utils_common import dlc, plot_data
# from plt_one_addpt_onclick import plt_one_addpt_onclick
# plt.style.use('./deeplearning.mplstyle')

In [24]:
# x_train -> One variable 

x_train = np.array([0., 1, 2, 3, 4, 5])
y_train = np.array([0, 0, 0, 1, 1, 1,])

# X_train2 -> Multiple variable 
X_train2 = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y_train2 = np.array([0, 0, 0, 1, 1, 1])

print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of x_train: {X_train2.shape}")

Shape of x_train: (6,)
Shape of x_train: (6, 2)


In [ ]:
pos = y_train == 1 # only true which are y_train[i] == 1
neg = y_train == 0 # only true which are y_train[i] == 0
pos2 = y_train2 == 1  # For the second plot
neg2 = y_train2 == 0  # For the second plot
[pos, y_train, neg, y_train]

[array([False, False, False,  True,  True,  True]),
 array([0, 0, 0, 1, 1, 1]),
 array([ True,  True,  True, False, False, False]),
 array([0, 0, 0, 1, 1, 1])]