### **Code explanations:**

In [2]:
import numpy as np
np.set_printoptions(precision=2)
arr = np.array([3.14159, 2.71828, 1.41421])
print(arr)

[3.14 2.72 1.41]


The `np.set_printoptions(precision=2)` function in NumPy sets the number of decimal places to display for floating-point numbers in arrays to 2.

In [3]:
a = np.array([9, 7, 4, 5])
b = np.array([7, 3, 1, 6])


ans = np.dot(a, b)
# ans = [(9*7) + (7*3) + (4*1) + (5*6)]
# ans = [63 + 21 + 4 + 30]
# ans = 118
print(ans)

118


In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

ans = np.dot(A, B)
# The dot product of two matrices A and B results in a new matrix C,
# where each element C[i, j] is the dot product of the i-th row of A
# and the j-th column of B.

# C[0,0] = (A[0,0]*B[0,0]) + (A[0,1]*B[1,0]) + (A[0,2]*B[2,0])
#        = (1*9) + (2*6) + (3*3) = 9 + 12 + 9 = 30
# C[0,1] = (A[0,0]*B[0,1]) + (A[0,1]*B[1,1]) + (A[0,2]*B[2,1])
#        = (1*8) + (2*5) + (3*2) = 8 + 10 + 6 = 24
# C[0,2] = (A[0,0]*B[0,2]) + (A[0,1]*B[1,2]) + (A[0,2]*B[2,2])
#        = (1*7) + (2*4) + (3*1) = 7 + 8 + 3 = 18

# C[1,0] = (A[1,0]*B[0,0]) + (A[1,1]*B[1,0]) + (A[1,2]*B[2,0])
#        = (4*9) + (5*6) + (6*3) = 36 + 30 + 18 = 84
# C[1,1] = (A[1,0]*B[0,1]) + (A[1,1]*B[1,1]) + (A[1,2]*B[2,1])
#        = (4*8) + (5*5) + (6*2) = 32 + 25 + 12 = 69
# C[1,2] = (A[1,0]*B[0,2]) + (A[1,1]*B[1,2]) + (A[1,2]*B[2,2])
#        = (4*7) + (5*4) + (6*1) = 28 + 20 + 6 = 54

# C[2,0] = (A[2,0]*B[0,0]) + (A[2,1]*B[1,0]) + (A[2,2]*B[2,0])
#        = (7*9) + (8*6) + (9*3) = 63 + 48 + 27 = 138
# C[2,1] = (A[2,0]*B[0,1]) + (A[2,1]*B[1,1]) + (A[2,2]*B[2,1])
#        = (7*8) + (8*5) + (9*2) = 56 + 40 + 18 = 114
# C[2,2] = (A[2,0]*B[0,2]) + (A[2,1]*B[1,2]) + (A[2,2]*B[2,2])
#        = (7*7) + (8*4) + (9*1) = 49 + 32 + 9 = 90

# ans = [[30, 24, 18],
#        [84, 69, 54],
#        [138, 114, 90]]
print(ans)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

ans = A@B
print(ans)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# B visually looks like a row matrix but it is actually a columan matrix
B = np.array([10, 20, 30])

# A(3x3) & B(1x3)
print(A.shape, B.shape)
ans = A @ B
print(ans)

(3, 3) (3,)
[140 320 500]
