### **Slicing:**

In [6]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Sliced array:\n",A[0:])
print("Shape of sliced array:", A[0:].shape)
print("Dimension of sliced array:",A[0:].ndim)

Sliced array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of sliced array: (3, 3)
Dimension of sliced array: 2


In [7]:
print("Sliced array:\n",A[1:])
print("Shape of sliced array:", A[1:].shape)
print("Dimension of sliced array:",A[1:].ndim)

Sliced array:
 [[4 5 6]
 [7 8 9]]
Shape of sliced array: (2, 3)
Dimension of sliced array: 2


In [8]:
print("Sliced array:\n",A[2:])
print("Shape of sliced array:", A[2:].shape)
print("Dimension of sliced array:",A[2:].ndim)

Sliced array:
 [[7 8 9]]
Shape of sliced array: (1, 3)
Dimension of sliced array: 2


In [12]:
print("Sliced array:\n",A[0:1])
print("Shape of sliced array:", A[0:1].shape)
print("Dimension of sliced array:",A[0:1].ndim)

Sliced array:
 [[1 2 3]]
Shape of sliced array: (1, 3)
Dimension of sliced array: 2


In [13]:
print("Sliced array:\n",A[0:2])
print("Shape of sliced array:", A[0:2].shape)
print("Dimension of sliced array:",A[0:2].ndim)

Sliced array:
 [[1 2 3]
 [4 5 6]]
Shape of sliced array: (2, 3)
Dimension of sliced array: 2


In [14]:
print("Sliced array:\n",A[0:3])
print("Shape of sliced array:", A[0:3].shape)
print("Dimension of sliced array:",A[0:3].ndim)

Sliced array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of sliced array: (3, 3)
Dimension of sliced array: 2


In [17]:
print("Sliced array:\n",A[0:3,0:3])
print("Shape of sliced array:", A[0:3,0:3].shape)
print("Dimension of sliced array:",A[0:3,0:3].ndim)

Sliced array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of sliced array: (3, 3)
Dimension of sliced array: 2


In [15]:
print("Sliced array:\n",A[0:3,0:2])
print("Shape of sliced array:", A[0:3,0:2].shape)
print("Dimension of sliced array:",A[0:3,0:2].ndim)

Sliced array:
 [[1 2]
 [4 5]
 [7 8]]
Shape of sliced array: (3, 2)
Dimension of sliced array: 2


In [18]:
print("Sliced array:\n",A[0:3,0:1])
print("Shape of sliced array:", A[0:3,0:1].shape)
print("Dimension of sliced array:",A[0:3,0:1].ndim)

Sliced array:
 [[1]
 [4]
 [7]]
Shape of sliced array: (3, 1)
Dimension of sliced array: 2


In [19]:
print("Sliced array:\n",A[0:2,1:3])
print("Shape of sliced array:", A[0:2,1:3].shape)
print("Dimension of sliced array:",A[0:2,1:3].ndim)

Sliced array:
 [[2 3]
 [5 6]]
Shape of sliced array: (2, 2)
Dimension of sliced array: 2


In [20]:
print("Sliced array:\n",A[0,:])
print("Shape of sliced array:", A[0,:].shape)
print("Dimension of sliced array:",A[0,:].ndim)

Sliced array:
 [1 2 3]
Shape of sliced array: (3,)
Dimension of sliced array: 1


In [21]:
print("Sliced array:\n",A[1,:])
print("Shape of sliced array:", A[1,:].shape)
print("Dimension of sliced array:",A[1,:].ndim)

Sliced array:
 [4 5 6]
Shape of sliced array: (3,)
Dimension of sliced array: 1


In [22]:
print("Sliced array:\n",A[2,:])
print("Shape of sliced array:", A[2,:].shape)
print("Dimension of sliced array:",A[2,:].ndim)

Sliced array:
 [7 8 9]
Shape of sliced array: (3,)
Dimension of sliced array: 1
