In [2]:
import numpy as np
import pandas as pd

* H(p) = 0 when p=0 & p=1
* H(p) = 1 when p=0.5
* Here H(p) is entropy & p is the fraction of positive class

In [3]:
X_train = np.array([[1, 1, 1],
[0, 0, 1],
 [0, 1, 0],
 [1, 0, 1],
 [1, 1, 1],
 [1, 1, 0],
 [0, 0, 0],
 [1, 1, 0],
 [0, 1, 0],
 [0, 1, 0]])

y_train = np.array([1, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [20]:
def entropy(p):
    if p == 0 or p == 1:
        return 0
    else:
        return -(p * np.log2(p) + (1-p)*np.log2(1-p))

print(entropy(0.5))

1.0


In [ ]:
# first raw -> ear shape
# second raw -> face shape
# third raw -> whiskers
# ear shape = 1 if pointy else floppy
for i, x in enumerate(X_train):
    print(i, x)

0 [1 1 1]
1 [0 0 1]
2 [0 1 0]
3 [1 0 1]
4 [1 1 1]
5 [1 1 0]
6 [0 0 0]
7 [1 1 0]
8 [0 1 0]
9 [0 1 0]


In [8]:
index_feature = 0
for i, x in enumerate(X_train):
    print(i, x[index_feature] == 1)

0 True
1 False
2 False
3 True
4 True
5 True
6 False
7 True
8 False
9 False


In [9]:
def split_indeces(X, index_features):
    """ index_features = 1st row
        checking the if pointy or not.
        if pointy then go to left else right.
    """
    left_indeces = []
    right_indeces = []

    for i, x in enumerate(X):

        if x[index_features] == 1: # checking only first row for pointy or not
            left_indeces.append(i)
        else:
            right_indeces.append(i)

    return left_indeces, right_indeces

In [10]:
split_indeces(X_train, 0)

([0, 3, 4, 5, 7], [1, 2, 6, 8, 9])

In [11]:
left, right = split_indeces(X_train, 0)

In [ ]:
print(y_train)
print(y_train[left]) # 4 cat 1 dog
print(y_train[right]) # 1 cat 4 dog
# w_left = 5 / 10 & p_left = 4 / 5
# w_right = 5 / 10 & p_right = 1 / 5

[1 1 0 0 1 1 0 1 0 0]
[1 0 1 1 1]
[1 0 0 0 0]


In [23]:
def weighted_entropy(X, y, left_indices, right_indices):
    w_left = len(left_indices) / len(X)
    w_right = len(right_indices) / len(X)
    p_left = sum(y[left_indices]) / len(left_indices)
    p_right = sum(y[right_indices]) / len(right_indices)

    weighted_entropy = w_left * entropy(p_left) + w_right * entropy(p_right)
    return weighted_entropy

In [24]:
left_indices, right_indices = split_indeces(X_train, 0)
weighted_entropy(X_train, y_train, left_indices, right_indices)

np.float64(0.7219280948873623)