In [139]:
import math, copy
import numpy as np
import matplotlib.pyplot as plt

In [140]:
X_train = np.array([[2104, 5, 1, 45], 
                    [1416, 3, 2, 40], 
                    [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [141]:
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"X_train[0]: {X_train.shape[0]}")
print(f"X_train[1]: {X_train.shape[1]}")

Shape of X_train: (3, 4)
Shape of y_train: (3,)
X_train[0]: 3
X_train[1]: 4


In [142]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [143]:
x = [10, 20, 30]
y = [10, 20, 30]
ans = x + y 
print(ans)

[10, 20, 30, 10, 20, 30]


In [144]:
print(X_train[2])

[852   2   1  35]


In [145]:
def model_0(x, y, w, b):
    n = x.shape[0]
    f_wb = np.zeros(0)
    for i in range(n):
        f_wb = np.append(f_wb, w @ x[i] + b)
    return f_wb 

In [146]:
f_wb_i = model_0(X_train, y_train, w_init, b_init)
f_wb_i

array([459.99999762, 231.99999837, 177.99999899])

In [147]:
def model_1(x, w, b):
    # number of traning examples 
    m = x.shape[0]
    f_wb = 0
    for i in range(m):
        f_wb += (x[i] * w[i])

    f_wb = f_wb + b
    return f_wb 

In [148]:
# predict from the 1st traning example
training_example_1 = X_train[0,:]
print(f"training_example_1.shape: {training_example_1.shape}")
print(f"training_example_1's value: {training_example_1}")

# make a prediction with the first training example 
f_wb = model_1(training_example_1, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}, actual value: {y_train[0]}")
print(f"")

training_example_1.shape: (4,)
training_example_1's value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083, actual value: 460



In [149]:
# predict from the 2nd traning example
training_example_2 = X_train[1,:]
print(f"training_example_1.shape: {training_example_2.shape}")
print(f"training_example_1's value: {training_example_2}")

# make a prediction with the first training example 
f_wb = model_1(training_example_2, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}, actual value: {y_train[1]}")

training_example_1.shape: (4,)
training_example_1's value: [1416    3    2   40]
f_wb shape (), prediction: 231.9999983694081, actual value: 232


In [150]:
# Model_3 using dot function 
def model_2(x, w, b):
    f_wb = x @ w
    f_wb += b
    return f_wb 

In [151]:
# predict from the 1st traning example
training_example_1 = X_train[0,:]
print(f"training_example_1.shape: {training_example_1.shape}")
print(f"training_example_1's value: {training_example_1}")

# make a prediction with the first training example 
ans = model_2(training_example_1, w_init, b_init)
print(f"f_wb shape {ans.shape}, prediction: {ans}, actual value: {y_train[0]}")
print(f"")

training_example_1.shape: (4,)
training_example_1's value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083, actual value: 460



In [152]:
# Manually calculating cost: 
print(X_train[0,:] @ w_init + b_init)
print(X_train[1,:] @ w_init + b_init)
print(X_train[2,:] @ w_init + b_init)
print(y_train)


459.9999976194083
231.9999983694081
177.99999898940814
[460 232 178]


In [153]:
def compute_cost(x, y, w, b):
    # number of training examples 
    m = x.shape[0]
    mse = 0
    for i in range(m):
        f_wb_i = x[i, :] @ w + b
        se = (f_wb_i - y[i]) ** 2
        mse = mse + se 
    
    cost = mse / (2*m)
    return cost 

In [154]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f"Cost at optimal w: {cost}")

Cost at optimal w: 1.5578904428966628e-12
