**Importing library:**

In [56]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from lab_utils_multi import load_house_data
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)

- Load the dataset

In [57]:
X_train = np.array([1.0, 2.0]) # features
y_train = np.array([300, 500])

In [58]:
print(X_train.ndim)
print(X_train.shape)

1
(2,)


In [59]:
print(X_train.reshape(-1,1))
print(X_train.reshape(-1,1).ndim)
print(X_train.reshape(-1,1).shape)

[[1.]
 [2.]]
2
(2, 1)


- Create and fit the model

In [60]:
linear_model = LinearRegression()
# X must be a 2-D matrix
linear_model.fit(X_train.reshape(-1, 1), y_train)

LinearRegression()

- View parameters

In [61]:
b = linear_model.intercept_
w = linear_model.coef_
print(f"w = {w:}, b = {b:0.2f}")
print(f"'manual' prediction: f_wb = wx+b : {1200*w + b}")

w = [200.], b = 100.00
'manual' prediction: f_wb = wx+b : [240100.]


- Make prediction using `predict` functions

In [62]:
y_pred = linear_model.predict(X_train.reshape(-1, 1))

print("Prediction on training set:", y_pred)

Prediction on training set: [300. 500.]


- Predict using unseen data 

In [63]:
X_test = np.array([[1200]])
print(f"Prediction for 1200 sqft house: ${linear_model.predict(X_test)[0]:0.2f}")

Prediction for 1200 sqft house: $240100.00


- Second example with multiple features 

In [64]:
# load the dataset
X_train2, y_train2 = load_house_data()
X_features = ['size(sqft)','bedrooms','floors','age']
print(X_train2.shape)

(99, 4)


In [65]:
linear_model2 = LinearRegression()
linear_model2.fit(X_train2, y_train2)

LinearRegression()

In [66]:
b2 = linear_model2.intercept_
w2 = linear_model2.coef_
print(f"w = {w2:}, b = {b2:0.2f}")

w = [  0.27 -32.62 -67.25  -1.47], b = 220.42


In [67]:
print(f"Prediction on training set:\n {linear_model2.predict(X_train2)[:4]}" )
print(f"prediction using w,b:\n {(X_train2 @ w2 + b2)[:4]}")
print(f"Target values \n {y_train2[:4]}")

x_house = np.array([1200, 3,1, 40]).reshape(-1,4)
x_house_predict = linear_model2.predict(x_house)[0]
print(f" predicted price of a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old = ${x_house_predict*1000:0.2f}")

Prediction on training set:
 [295.18 485.98 389.52 492.15]
prediction using w,b:
 [295.18 485.98 389.52 492.15]
Target values 
 [300.  509.8 394.  540. ]
 predicted price of a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old = $318709.09


What learned: 
- `LinearRegression` class from `linear_model`
- `StandardScaler` class from `preprocessor`
- `scaler.fit_transform(X_train)` for normalization
- `LinearModel.fit(X_train, y_train)` for fitting data 
- `LinearModel.intercept_` for checking the intercept/bias
- `LinearModel.coef_` for checking coefficient/wieght

| Feature                | `LinearRegression`                        | `SGDRegressor`                             |
| :--------------------- | :---------------------------------------- | :----------------------------------------- |
| **Optimization** | Closed-form solution (OLS)                | Stochastic Gradient Descent (Iterative)    |
| **Solution Guarantee** | Global Minimum (exact)                    | Approximate Global Minimum (good enough)   |
| **Scalability** | Less scalable for very large datasets     | Highly scalable for very large datasets    |
| **Memory Usage** | Can be high for many features             | Lower, suitable for out-of-core learning   |
| **Hyperparameters** | Few (e.g., `fit_intercept`)               | Many (e.g., `learning_rate`, `max_iter`)   |
| **Performance** | Faster for small/medium datasets          | Faster for very large datasets             |
| **Common Use Case** | Smaller, in-memory datasets, analytical needs | Large datasets, online learning            |
