In [409]:
import math, copy
import numpy as np
import matplotlib.pyplot as plt

In [410]:
X_train = np.array([[2104, 5, 1, 45], 
                    [1416, 3, 2, 40], 
                    [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [411]:
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"X_train[0]: {X_train.shape[0]}")
print(f"X_train[1]: {X_train.shape[1]}")

Shape of X_train: (3, 4)
Shape of y_train: (3,)
X_train[0]: 3
X_train[1]: 4


In [412]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [413]:
x = [10, 20, 30]
y = [10, 20, 30]
ans = x + y 
print(ans)

[10, 20, 30, 10, 20, 30]


In [414]:
print(X_train[2])

[852   2   1  35]


In [415]:
def model_0(x, y, w, b):
    n = x.shape[0]
    f_wb = np.zeros(0)
    for i in range(n):
        f_wb = np.append(f_wb, w @ x[i] + b)
    return f_wb 

In [416]:
f_wb_i = model_0(X_train, y_train, w_init, b_init)
f_wb_i

array([459.99999762, 231.99999837, 177.99999899])

In [417]:
def model_1(x, w, b):
    # number of traning examples 
    m = x.shape[0]
    f_wb = 0
    for i in range(m):
        f_wb += (x[i] * w[i])

    f_wb = f_wb + b
    return f_wb 

In [418]:
# predict from the 1st traning example
training_example_1 = X_train[0,:]
print(f"training_example_1.shape: {training_example_1.shape}")
print(f"training_example_1's value: {training_example_1}")

# make a prediction with the first training example 
f_wb = model_1(training_example_1, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}, actual value: {y_train[0]}")
print(f"")

training_example_1.shape: (4,)
training_example_1's value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083, actual value: 460



In [419]:
# predict from the 2nd traning example
training_example_2 = X_train[1,:]
print(f"training_example_1.shape: {training_example_2.shape}")
print(f"training_example_1's value: {training_example_2}")

# make a prediction with the first training example 
f_wb = model_1(training_example_2, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}, actual value: {y_train[1]}")

training_example_1.shape: (4,)
training_example_1's value: [1416    3    2   40]
f_wb shape (), prediction: 231.9999983694081, actual value: 232


In [420]:
# Model_3 using dot function 
def model_2(x, w, b):
    f_wb = x @ w
    f_wb += b
    return f_wb 

In [421]:
# predict from the 1st traning example
training_example_1 = X_train[0,:]
print(f"training_example_1.shape: {training_example_1.shape}")
print(f"training_example_1's value: {training_example_1}")

# make a prediction with the first training example 
ans = model_2(training_example_1, w_init, b_init)
print(f"f_wb shape {ans.shape}, prediction: {ans}, actual value: {y_train[0]}")
print(f"")

training_example_1.shape: (4,)
training_example_1's value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083, actual value: 460



In [422]:
# Manually calculating cost: 
print(X_train[0,:] @ w_init + b_init)
print(X_train[1,:] @ w_init + b_init)
print(X_train[2,:] @ w_init + b_init)
print(y_train)


459.9999976194083
231.9999983694081
177.99999898940814
[460 232 178]


In [423]:
print((X_train[0,:] @ w_init + b_init) - y_train[0])
print((X_train[1,:] @ w_init + b_init) - y_train[1])
print((X_train[2,:] @ w_init + b_init) - y_train[2])

-2.380591695327894e-06
-1.6305918961734278e-06
-1.0105918590852525e-06


In [424]:
# Compute cost for multiple variable
def compute_cost(X, y, w, b):
    # number of training examples 
    m, _ = X.shape
    err = 0
    for i in range(m):
        f_wb_i = (w @ X[i]) + b
        err += (f_wb_i - y[i]) ** 2
    cost = err / (2 * m)
    return cost

In [425]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 1.5578904428966628e-12


In [426]:
# compute gradient for multiple variable 
def compute_gradient(X, y, w, b):
    # number of training examples & features 
    m, n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.
    for i in range(m):
        err = ((w @ X[i]) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * X[i, j]
        dj_db += err
    dj_dw = dj_dw / m
    dj_db = dj_db / m
    return dj_dw, dj_db

In [427]:
#Compute and display gradient 
dj_dw, dj_db = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {dj_db}')
print(f'dj_dw at initial w,b: \n {dj_dw}')

dj_db at initial w,b: -1.6739251501955248e-06
dj_dw at initial w,b: 
 [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]


In [428]:
# Compute gradient descent for multiple variables
import copy
def gradient_descent(X, y, w_in, b_in,
                    cost_function, gradient_function,
                    alpha, iterations):
    J_history = []
    w = copy.deepcopy(w_in)
    b = b_in
    for i in range(iterations):
        dj_dw, dj_db = gradient_function(X, y, w, b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
        if i < 100000:
            J_history.append(cost_function(X, y, w, b))
        if i % 100 == 0:
            print(f"Iterations of {i:4d}: cost is {J_history[-1]}")
    return w, b, J_history

In [429]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iterations of    0: cost is 2529.4629522316304
Iterations of  100: cost is 695.990315835203
Iterations of  200: cost is 694.9206979323061
Iterations of  300: cost is 693.8604297851192
Iterations of  400: cost is 692.8094286135915
Iterations of  500: cost is 691.7676123706057
Iterations of  600: cost is 690.7348997354997
Iterations of  700: cost is 689.711210107616
Iterations of  800: cost is 688.6964635999458
Iterations of  900: cost is 687.6905810327947
b,w found by gradient descent: -0.00,[ 0.20396569  0.00374919 -0.0112487  -0.0658614 ] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
