In [28]:
import numpy as np
import time 

- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)

In NumPy, **broadcasting** is a powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations.

Simply put, when you perform an operation (like addition, subtraction, multiplication) between two arrays that don't have the exact same shape, NumPy tries to "stretch" or "duplicate" the smaller array's dimensions to match the larger array's shape, as long as they are compatible.

### **Code example:**

In [29]:
import numpy as np

# Array 1: a 2x3 array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Array 2: a 1D array (scalar technically, but acts as a 1D array of shape (1,))
arr2 = np.array([10])

# Perform addition using broadcasting
result = arr1 + arr2

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nResult of broadcasting (arr1 + arr2):\n", result)

Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [10]

Result of broadcasting (arr1 + arr2):
 [[11 12 13]
 [14 15 16]]


In [30]:
a = np.zeros(4)
print(f"a      : {a}")
print(f"a.shape: {a.shape}") # returns tuple of size
print(f"a.ndim: {a.ndim}")

a      : [0. 0. 0. 0.]
a.shape: (4,)
a.ndim: 1


In [31]:
a = np.zeros(4,)
print(f"a      : {a}")
print(f"a.shape: {a.shape}")
print(f"a.ndim : {a.ndim}")

a      : [0. 0. 0. 0.]
a.shape: (4,)
a.ndim : 1


In [32]:
a = np.ones((4,2)) # takes 
print(f"a      : \n{a}")
print(f"a.shape: {a.shape}")
print(f"a.ndim : {a.ndim}")

a      : 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
a.shape: (4, 2)
a.ndim : 2


- `np.random.random_sample()` -> takes integer or tuple as size.
- `np.random.sample()` -> takes integer or tuple as size.
- `np.random.rand` -> directly takes dimension as size
- output ranges: ```[0,1)``` 

In [33]:
a = np.random.random_sample((4,)) # takes tuple as input size
print(f"a       : {a}")
print(f"a.shape : {a.shape}")
print(f"a.ndim  : {a.ndim}")

a       : [0.71722906 0.52594785 0.7891878  0.72678226]
a.shape : (4,)
a.ndim  : 1


In [34]:
a = np.random.rand(4,3) # takes tuple as input size
print(f"a       : \n{a}")
print(f"a.shape : {a.shape}")
print(f"a.ndim  : {a.ndim}")

a       : 
[[0.29798649 0.84788784 0.83281046]
 [0.25250757 0.14154484 0.9132712 ]
 [0.5013724  0.21127136 0.38309034]
 [0.34404785 0.22099769 0.88378781]]
a.shape : (4, 3)
a.ndim  : 2


In [35]:
a = np.array([5, 3, 4, 2]) # takes list as input 
print(f"a       : {a}")
print(f"a.shape : {a.shape}")
print(f"a.ndim  : {a.ndim}")

a       : [5 3 4 2]
a.shape : (4,)
a.ndim  : 1


In [36]:
a = np.array([5., 3, 4, 2]) # takes list as input 
print(f"a       : {a}")
print(f"a.shape : {a.shape}")
print(f"a.ndim  : {a.ndim}")

a       : [5. 3. 4. 2.]
a.shape : (4,)
a.ndim  : 1


In [37]:
a = np.arange(4)
print(f"a       : {a}")
print(f"a.shape : {a.shape}")
print(f"a.ndim  : {a.ndim}")

a       : [0 1 2 3]
a.shape : (4,)
a.ndim  : 1


In [38]:
a = np.arange(4)
print(f"a[2]       : {a[2]}")
print(f"a[2].shape : {a[2].shape}")
print(f"a[2].ndim  : {a[2].ndim}")

a[2]       : 2
a[2].shape : ()
a[2].ndim  : 0


**Access the last element:**

In [39]:
a = np.arange(4)
print(f"a[-1]       : {a[-1]}")
print(f"a[-1].shape : {a[-1].shape}")
print(f"a[-1].ndim  : {a[-1].ndim}")

a[-1]       : 3
a[-1].shape : ()
a[-1].ndim  : 0


In [40]:
a = np.arange(4)
try:
    print(f"a[5]       : {a[5]}")
except Exception as e:
    print(f"The error message you'll see is:\n{e}")

The error message you'll see is:
index 5 is out of bounds for axis 0 with size 4


**Slicing 1D array:  `array[start: stop: step]`**

In [ ]:
a = np.arange(10)

# Access 5 consecutive elements
print(a[0:5:1])

# access 3 elements separated by 2
print(a[0:5: 2])

# access all elements index 3 and above 
print(a[3:])

# access all elements below 3
print(a[:3])

# access all elements 
print(a[:])

[0 1 2 3 4]
[0 2 4]
[3 4 5 6 7 8 9]
[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


**Reverse the array:**

In [73]:
a = np.arange(5)

# reverse the array using slicing 
print(a[4::-1])
print(a[::-1]) # this is also possible for negative indexing 

[4 3 2 1 0]
[4 3 2 1 0]


**Single vector operations:**

In [49]:
a = np.array([1, 2, 3, 4])

# Negate elements of a
b = -a 
print(f"Negate elements of b: {b}")

# Sum all elements of a, returns scalar
a_sum = np.sum(a)
print(f"Sum all elements of a returns a scalar: {a_sum}")

# Mean of a 
a_mean = np.mean(a)
print(f"Mean of a: {a_mean}")

# All squared value of a 
a_squared = a ** 2
print(f"All squared value of a: {a_squared}")

Negate elements of b: [-1 -2 -3 -4]
Sum all elements of a returns a scalar: 10
Mean of a: 2.5
All squared value of a: [ 1  4  9 16]


**Vector element wise operations:**

In [50]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: \n{a + b}")

Binary operators work element wise: 
[0 0 6 8]


In [51]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [52]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


**Vector dot product:**

In [ ]:
# Dot product using loop 
def my_dot(a, b):
    dot_prod = 0
    for i in range(a.shape[0]):
        dot_prod += a[i] * b[i]
    
    return dot_prod

In [ ]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [57]:
# Dot product using method

# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"Dot product using method = {np.dot(a,b)}")
print(f"Dot product using method = {np.dot(b,a)}")

Dot product using method = 24
Dot product using method = 24


**Matrix or 2D array creation:**

In [59]:
a = np.zeros((3,4))
print(f"a        : \n{a}")
print(f"a.shape  : {a.shape}")
print(f"a.ndim   : {a.ndim}\n")

a = np.ones((2,2))
print(f"a        : \n{a}")
print(f"a.shape  : {a.shape}")
print(f"a.ndim   : {a.ndim}\n")

a = np.random.sample((3,5))
print(f"a        : \n{a}")
print(f"a.shape  : {a.shape}")
print(f"a.ndim   : {a.ndim}\n")

a        : 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a.shape  : (3, 4)
a.ndim   : 2

a        : 
[[1. 1.]
 [1. 1.]]
a.shape  : (2, 2)
a.ndim   : 2

a        : 
[[0.71606686 0.48214994 0.50807907 0.16212185 0.21432328]
 [0.57002162 0.11071421 0.85474735 0.00894788 0.08539391]
 [0.72593886 0.28657992 0.61683278 0.717616   0.86790782]]
a.shape  : (3, 5)
a.ndim   : 2



In [62]:
a = np.array([[5],  
              [4],  
              [3]]); 
print(f" a shape = {a.shape}, \nnp.array: a = \n{a}")

 a shape = (3, 1), 
np.array: a = 
[[5]
 [4]
 [3]]



**2D array slicing & indexing:**

`
array[row_start: row_stop: row_step,column_start: column_stop: column_step]
`

This is like:

`python
array[rows, columns]
`

In [72]:
a = np.arange(20).reshape(-1, 5)
print(a[3, 4])

print(f"a[2,]       : {a[2,]}")
print(f"a[2,].shape : {a[2,].shape}\n")

print(f"a[2,]       : \n{a[1:3,1:4]}")


19
a[2,]       : [10 11 12 13 14]
a[2,].shape : (5,)

a[2,]       : 
[[ 6  7  8]
 [11 12 13]]


**Reverse 2D array:**

In [75]:
a = np.arange(12).reshape(-1, 4)
print(f"a       : \n{a}")
print(f"row column reversed: \n{a[::-1, ::-1]}")

a       : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row column reversed: 
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
