<center>

#### **Python, NumPy and Vectorization** 
---

</center>

In [2]:
import numpy as np
import time 

**Useful References:**

- NumPy Documentation including a basic introduction: [NumPy.org](https://NumPy.org/doc/stable/)
- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)

**Vector:** The elements of vectors are all the same datatype.
>Note: A vector does not contain both characters and numbers.

**NumPy Arrays:** NumPy's basic data structure is an indexable, `n-dimensinal` array. (same data type `dtype`)

- Vectors are 1-D arrays 

In [10]:
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample((4,)); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.ones(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.98109237 0.39219959 0.96382818 0.12257602], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.73231858 0.79800617 0.65434911 0.01077968], a shape = (4,), a data type = float64
np.zeros(4) :   a = [1. 1. 1. 1.], a shape = (4,), a data type = float64


> Note: NumPy's default datatype is float64
---

**Some data creation routines do not take a shape tuple:**

In [6]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.25695437 0.33194145 0.44763692 0.60942211], a shape = (4,), a data type = float64


> Note : `np.arange()` & `np.random.rand()` don't take shape as input.
--- 

**Values can be specified manually as well:** 

In [7]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


> Note: If only one value is float then all will become float.
---

**Operations on Vectos:**

In [ ]:
a = np.arange(10)
print(f"Elements of a: {a}")
print(f"Data type of a: {a.dtype}")
print(f"Shape of a: {a.shape}")
print(f"Dimension of a: {a.ndim}")
print(f"Shape of a[2]: {a[2].shape}") # No shape for single value

Elements of a: [0 1 2 3 4 5 6 7 8 9]
Data type of a: int64
Shape of a: (10,)
Dimension of a: 1
Shape of a[2]: ()


In [15]:
a = np.arange(10)

print(f"Value of a[3]: {a[3]}")
print(f"Value of a[-1]: {a[-1]}") # Negative indexing 

try:
    c = a[0] # It's not out of index range 
except Exception as e:
    print("The error message you'll see is: ")
    print(e)

Value of a[3]: 3
Value of a[-1]: 9


In [17]:
a = np.arange(10)

print(f"Value of a[3]: {a[3]}")
print(f"Value of a[-1]: {a[-1]}") # Negative indexing 

try:
    c = a[15] # It's not out of index range 
except Exception as e:
    print("The error message you'll see is: ")
    print(e)

Value of a[3]: 3
Value of a[-1]: 9
The error message you'll see is: 
index 15 is out of bounds for axis 0 with size 10


**Slicing:** b = `a[start: stop: stpe]`

In [19]:
a = np.arange(10)
print(f"Elements of a : {a}")

# acces 5 consecutive elements 
c = a[2:7:1]; print(f"a[2:7:1] : {c}")

# access 3 element separated by 2
c = a[3:8:2]; print(f"a[3:8:2] : {c}")

# access all element index 3 and above 
c = a[3::];   print(f"a[3::]   : {a}")

# access all elements below index 3
c = a[:3:];   print(f"a[:3:]   : {c}")

# access all elements 
c = a[::];    print(f"a[::]    : {c}")

Elements of a : [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] : [2 3 4 5 6]
a[3:8:2] : [3 5 7]
a[3::]   : [0 1 2 3 4 5 6 7 8 9]
a[:3:]   : [0 1 2]
a[::]    : [0 1 2 3 4 5 6 7 8 9]


**Single Vector operations:**

In [20]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


**Vector Vector element-wise operations:**
$$ c_i = a_i + b_i $$
$$\mathbf{c} =[ (a_1 + b_1)(a_2 + b_2)(a_3 + b_3) \dots (a_n + b_n) ]$$
> Note: Vectors must be of the same size.

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(f"Binary operations work element wise: {a + b}")

Binary operations work element wise: [0 0 6 8]


In [22]:
# Trying mismatched vector operation

c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you will see is: ")
    print(e)

The error message you will see is: 
operands could not be broadcast together with shapes (4,) (2,) 


**Scalar Vector Operations:** 

In [23]:
a = np.array([1, 2, 3, 4])
b = 5 * a
c = 5 + a
d = a - 5 
print(f"Elements of a: {a}")
print(f"Elements of b: {b}")
print(f"Elements of c: {c}")
print(f"Elements of d: {d}")

Elements of a: [1 2 3 4]
Elements of b: [ 5 10 15 20]
Elements of c: [6 7 8 9]
Elements of d: [-4 -3 -2 -1]


**Matrix Creation:**

In [4]:
import numpy as np
a = np.zeros((1, 5))
print(f"A shape = {a.shape}, \na = {a}")

a = np.zeros((2, 1))
print(f"a shape = {a.shape}, \na = {a}")

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, \na = {a}")

A shape = (1, 5), 
a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), 
a = [[0.]
 [0.]]
a shape = (1, 1), 
a = [[0.24225482]]


In [5]:
a = np.array([[1], [2], [3]])
print(f"a.shape: {a.shape}, \na = {a}")

a = np.array([
    [1, 2],
    [3, 4]])

print(f"a.shape: {a.shape}, \na = {a}")

a.shape: (3, 1), 
a = [[1]
 [2]
 [3]]
a.shape: (2, 2), 
a = [[1 2]
 [3 4]]


In [10]:
a = np.arange(6).reshape(-1, 2)
print(f"a.shape: {a.shape}, \na= \n{a}")

print(a[2, 0])
print(a[2])

a.shape: (3, 2), 
a= 
[[0 1]
 [2 3]
 [4 5]]
4
[4 5]


**Matrix Slicing:**

In [ ]:
# [[ 0  1  2  3  4]   ---> 0
#  [ 5  6  7  8  9]   ---> 1
#  [10 11 12 13 14]   ---> 2
#  [15 16 17 18 19]   ---> 3
#  [20 21 22 23 24]   ---> 4
#  [25 26 27 28 29]]  ---> 5

# We can consider index as an array

a = np.arange(30).reshape(-1, 5) # (6, 5)

# print 3 consecutive row [maybe 2 to 4]
print(f"a[2:5:]: \n {a[2:5:]}\n")

# print 3 consecutive row with two step
print(f"a[2:5:]: \n {a[::2]}\n")


a[2:5:]: 
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

a[2:5:]: 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]



In [ ]:
# print from the middle 
print(a[2:5, 1:4])

[[11 12 13]
 [16 17 18]
 [21 22 23]]


In [22]:
# print all
print(a[:,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [23]:
# print 1st row
print(a[0,:])

[0 1 2 3 4]
