In [1]:
import numpy as np

In [3]:
a = np.zeros(4); print(f"np.zeros(4) : a = {a}"); print(f"a shape = {a.shape}"); print(f"a data type = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.]
a shape = (4,)
a data type = float64


In [ ]:
a = np.zeros((4,))
print(f"np.zeros((4,)) : a {a}")
print(f"a shape : {a.shape}")
print(f"a data type : {a.dtype}")

np.zeros((4,)) : a [0. 0. 0. 0.]
a shape : (4,)
a data type : float64


In [ ]:
a = np.random.random_sample(4)
# Generate random floats less than 1
print(f"np.random.random_sample(4): a = {a}")
print(f"a shape : {a.shape}")
print(f"a data type: {a.dtype}")

np.random.random_sample(4): a = [0.97445833 0.84431158 0.05325321 0.36024662]
a shape : (4,)
a data type: float64


In [16]:
a = np.arange(4.0) # float
print(f"np.arange(4.0) : a = {a}")
print(f"a shape = {a.shape}")
print(f"a data type = {a.dtype}")

np.arange(4.0) : a = [0. 1. 2. 3.]
a shape = (4,)
a data type = float64


In [ ]:
a = np.random.rand(4) # random floats less than 1
print(f"np.random.rand(4): a = {a}")
print(f"a shape = {a.shape}")
print(f"a data type = {a.dtype}")

np.random.rand(4): a = [0.43924833 0.2850675  0.41086991 0.64617984]
a shape = (4,)
a data type = float64


In [22]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}")

a[2].shape: () a[2] = 2


In [ ]:
print(f"a[-1] = {a[-1]}")

a[-1] = 9


In [25]:
a = np.arange(10)
print(f"a = {a}")

a = [0 1 2 3 4 5 6 7 8 9]


In [27]:
c = a[2:7:1]
print(c)

[2 3 4 5 6]


In [ ]:
a = np.array([1,2,3,4])
print(f"a : {a}")

b = -a # assign with negative a
print(f"b = -a : {b}")

a : [1 2 3 4]
b = -a : [-1 -2 -3 -4]


In [29]:
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.sum(a) : 10


In [ ]:
b = np.mean(a)
print(f"b = np.mean(a) : {b}")

b = np.mean(a) : 2.5


In [32]:
b = a**2
print(f"b = a**2 : {b}")

b = a**2 : [ 1  4  9 16]


In [33]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])

print(a + b)

[0 0 6 8]


In [34]:
print(a * b)

[-1 -4  9 16]


In [35]:
print(np.dot(a,b))

20


In [37]:
c = np.array([1,2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is: ")
    print(e)

The error message you'll see is: 
operands could not be broadcast together with shapes (4,) (2,) 


In [39]:
a = np.array([1,2,3,4])
n = 5 * a 
print(n)

[ 5 10 15 20]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])

def my_dot(a,b):
    x = 0
    for i in range(4):
        x += a[i] * b[i]
    
    return x

x = my_dot(a,b)
print(x)

20


In [52]:
def my_dot(a,b):
    x = 0
    for i in range(a.shape[0]):
        x += a[i] * b[i]
    
    return x

In [53]:
import time
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 5.0492 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 1839.0126 ms 


In [48]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

my_dot(a, b) =  1.0592
loop version duration: 0.0000 ms 


In [60]:
x = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])
print(f"Shape of x: {x.shape}")
print(f"Shape of x[1]: {x[0].shape}")
print(f"Shape of x[2]: {x[1].shape}")
print(f"Shape of x[3]: {x[2].shape}")
print(f"Size of x: {x.shape[0]}")
print(f"Size of x[1]: {x.shape[1]}")

Shape of x: (3, 3)
Shape of x[1]: (3,)
Shape of x[2]: (3,)
Shape of x[3]: (3,)
Size of x: 3
Size of x[1]: 3


In [ ]:
# ki koy