In [1]:
import numpy as np

In [3]:
a = np.zeros(4); print(f"np.zeros(4) : a = {a}"); print(f"a shape = {a.shape}"); print(f"a data type = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.]
a shape = (4,)
a data type = float64


In [ ]:
a = np.zeros((4,))
print(f"np.zeros((4,)) : a {a}")
print(f"a shape : {a.shape}")
print(f"a data type : {a.dtype}")

np.zeros((4,)) : a [0. 0. 0. 0.]
a shape : (4,)
a data type : float64


In [ ]:
a = np.random.random_sample(4)
# Generate random floats less than 1
print(f"np.random.random_sample(4): a = {a}")
print(f"a shape : {a.shape}")
print(f"a data type: {a.dtype}")

np.random.random_sample(4): a = [0.97445833 0.84431158 0.05325321 0.36024662]
a shape : (4,)
a data type: float64


In [16]:
a = np.arange(4.0) # float
print(f"np.arange(4.0) : a = {a}")
print(f"a shape = {a.shape}")
print(f"a data type = {a.dtype}")

np.arange(4.0) : a = [0. 1. 2. 3.]
a shape = (4,)
a data type = float64


In [ ]:
a = np.random.rand(4) # random floats less than 1
print(f"np.random.rand(4): a = {a}")
print(f"a shape = {a.shape}")
print(f"a data type = {a.dtype}")

np.random.rand(4): a = [0.43924833 0.2850675  0.41086991 0.64617984]
a shape = (4,)
a data type = float64


In [22]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}")

a[2].shape: () a[2] = 2


In [ ]:
print(f"a[-1] = {a[-1]}")

a[-1] = 9


In [25]:
a = np.arange(10)
print(f"a = {a}")

a = [0 1 2 3 4 5 6 7 8 9]


In [27]:
c = a[2:7:1]
print(c)

[2 3 4 5 6]


In [ ]:
a = np.array([1,2,3,4])
print(f"a : {a}")

b = -a # assign with negative a
print(f"b = -a : {b}")

a : [1 2 3 4]
b = -a : [-1 -2 -3 -4]


In [29]:
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.sum(a) : 10


In [ ]:
b = np.mean(a)
print(f"b = np.mean(a) : {b}")

b = np.mean(a) : 2.5


In [32]:
b = a**2
print(f"b = a**2 : {b}")

b = a**2 : [ 1  4  9 16]


In [33]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])

print(a + b)

[0 0 6 8]


In [34]:
print(a * b)

[-1 -4  9 16]


In [35]:
print(np.dot(a,b))

20


In [37]:
c = np.array([1,2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is: ")
    print(e)

The error message you'll see is: 
operands could not be broadcast together with shapes (4,) (2,) 
