In [22]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')

In [23]:
X_train = np.array([
    [2104, 5, 1, 45], 
    [1416, 3, 2, 40], 
    [852, 2, 1, 35]
    ])
y_train = np.array([460, 232, 178])

In [24]:
X_train[0,:]


array([2104,    5,    1,   45])

In [25]:
X_train[0]

array([2104,    5,    1,   45])

In [26]:
print(f"X Shape: {X_train.shape} \nX Type: {type(X_train)}\n")
print(X_train, end='\n\n')
print(f"y Shape: {y_train.shape} \ny Type: {type(y_train)}\n")
print(y_train)

X Shape: (3, 4) 
X Type: <class 'numpy.ndarray'>

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]

y Shape: (3,) 
y Type: <class 'numpy.ndarray'>

[460 232 178]


In [27]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [36]:
M = np.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
])
t = M.shape
t
t[0]
t[1]

4

In [40]:
# from class 8
# spent 4 hours daily
y = 6 # years
d = 365 # days
time_waste = 5 # hours 
days = 24 # 24 hours = 1 day

total_hours_waste = y*d*time_waste
total_days_waste = total_hours_waste / days
print(f"Total waste in hours: {total_hours_waste} hours")
print(f"Total waste in days: {total_days_waste} days")

Total waste in hours: 10950 hours
Total waste in days: 456.25 days


In [43]:
X_train[0,:]
d = np.dot(X_train[0,:],w_init)
d

np.float64(-325.18113917999995)