In [2]:
import numpy as np
import time 

In [2]:
a = np.zeros(4); print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[0. 0. 0. 0.]
shape: (4,)
data type: float64


In [3]:
a = np.zeros((4,)); print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[0. 0. 0. 0.]
shape: (4,)
data type: float64


In [4]:
a = np.zeros((4,3)); print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (4, 3)
data type: float64


In [3]:
a = np.random.random_sample(4)
print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[0.19873232 0.00297171 0.30264923 0.73766279]
shape: (4,)
data type: float64


In [ ]:
# np.random.random_sample() -> distributed in the range [0, 1)
a = np.random.random_sample((3,3))
print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[[0.59948376 0.53248153 0.7843211 ]
 [0.52191107 0.8138829  0.93711713]
 [0.66312684 0.45435217 0.33594514]]
shape: (3, 3)
data type: float64


In [7]:
a = np.random.randint(low=0, high=10, size=(3, 3))
print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[[4 9 8]
 [8 6 7]
 [7 4 5]]
shape: (3, 3)
data type: int32
