In [2]:
import numpy as np
import time 

In [3]:
a = np.zeros(4); print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[0. 0. 0. 0.]
shape: (4,)
data type: float64


In [4]:
a = np.zeros((4,)); print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[0. 0. 0. 0.]
shape: (4,)
data type: float64


In [5]:
a = np.zeros((4,3)); print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (4, 3)
data type: float64


In [6]:
a = np.random.random_sample(4)
print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[0.76274397 0.608372   0.30869828 0.50252691]
shape: (4,)
data type: float64


In [7]:
# np.random.random_sample() -> distributed in the range [0, 1)
a = np.random.random_sample((3,3))
print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[[0.3021954  0.99977062 0.82955067]
 [0.59601356 0.61448351 0.30271871]
 [0.17520941 0.32805166 0.76517918]]
shape: (3, 3)
data type: float64


In [8]:
a = np.random.randint(low=0, high=10, size=(3, 3))
print(f"{a}\nshape: {a.shape}\ndata type: {a.dtype}")

[[3 7 5]
 [6 1 7]
 [2 3 1]]
shape: (3, 3)
data type: int32


In [9]:
a = np.zeros(4)


In [10]:
a

array([0., 0., 0., 0.])

In [11]:
a + 1

array([1., 1., 1., 1.])

In [12]:
np.zeros((4,))

array([0., 0., 0., 0.])

In [13]:
a = np.zeros(4); print(f"{a}\n{a.shape}\n{a.dtype}\n{a.ndim}")

[0. 0. 0. 0.]
(4,)
float64
1


In [14]:
a = np.zeros((4,3)); print(f"{a}\n{a.shape}\n{a.dtype}\n{a.ndim}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)
float64
2


In [15]:
a = np.zeros_like(1); print(a) # Takes list 

0


In [16]:
a = np.zeros_like([[1,2,3,4],[5,6,7,8]]); a 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
a = np.random.random_sample(4)
print(f"{a}\n{a.shape}\n{a.dtype}\n{a.ndim}")

[0.36855075 0.93060626 0.45693868 0.92106289]
(4,)
float64
1


In [18]:
a = np.random.random_sample((4,3))
print(f"{a}\n{a.shape}\n{a.dtype}\n{a.ndim}")

[[0.0313272  0.08307091 0.24483493]
 [0.700765   0.47484809 0.34118095]
 [0.01199706 0.95426064 0.63597847]
 [0.92090609 0.75613978 0.21305406]]
(4, 3)
float64
2


In [19]:
a = np.arange(10); print(a)

[0 1 2 3 4 5 6 7 8 9]


- Single Vector Operations


In [20]:
a = np.array([1,2,3,4])

In [21]:
print(a)

[1 2 3 4]


In [22]:
b = -a

In [23]:
print(b)

[-1 -2 -3 -4]


In [24]:
b = np.sum(a); print(b)
b = np.mean(a); print(b)
b = a**2; print(b)

10
2.5
[ 1  4  9 16]


In [25]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])

In [26]:
print(a+b); print(a-b); print(a*b); print(a/b)

[0 0 6 8]
[2 4 0 0]
[-1 -4  9 16]
[-1. -1.  1.  1.]


In [27]:
# dimension must be same for operations
a = np.array([1,2,3,4])
c = np.array([1,2])

try: 
    d = a / c
except Exception as e:
    print("Error message: ",e)


Error message:  operands could not be broadcast together with shapes (4,) (2,) 


In [34]:
def my_dot(a,b):
    res_prod = 0
    for i in range(len(a)):
        for j in range(len(b)):
            res_prod = res_prod + (a[i][j] * b[i][j])
    
    return res_prod

# a = np.array([1, 2, 3, 4])
# b = np.array([-1, 4, 3, 2])
a = np.arange(9).reshape(3,3)
b = np.arange(9).reshape(3,3)
# print(f"my_dot(a, b) = {my_dot(a, b)}")
print(np.dot(a,b))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [33]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

c = np.dot(a,b)
print(c,c.shape)

24 ()


In [37]:
X = np.array([
    [1],
    [2],
    [3],
    [4]])
w = np.array([[1,2,3,4]])
# print(X,w)
c = np.dot(X, w)
# X.ndim
print(c)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [35]:
X = np.array([[1,2,3,4]])
Y = np.array([
    [1],
    [2],
    [3],
    [4]])
c = np.dot(X, Y)

print(c)


[[30]]


In [40]:
a = np.zeros((1,5)); print(f"{a}\n{a.shape}\n\n")
a = np.zeros((2,1)); print(f"{a}\n{a.shape}\n\n")
a = np.random.random_sample((1,1)); print(f"{a}\n{a.shape}\n\n")

[[0. 0. 0. 0. 0.]]
(1, 5)


[[0.]
 [0.]]
(2, 1)


[[0.30636243]]
(1, 1)




In [43]:
a = np.arange(8).reshape(-1,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [44]:
print(a[2,0])

4


In [45]:
print(a[2])

[4 5]


In [47]:
a = np.arange(20).reshape(-1,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [ ]:
print(a[0, 2:7])

[2 3 4 5 6]


In [49]:
print(a[1, 2:7])

[12 13 14 15 16]


In [51]:
print(a[:,:])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [52]:
print(a[1,:])

[10 11 12 13 14 15 16 17 18 19]


In [53]:
print(a[1])

[10 11 12 13 14 15 16 17 18 19]
